preserve_hierarchy: false
files:
  - source: /assets/*.*
    translation: /%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        vi: assets
  - source: /src/**/*.*
    translation: /%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        vi: src
